# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
#  repository: arilot/docker-bitcoind
  repository: 10.103.4.198:5000/kevinstl/lightning-kube-bitcoind
#  tag: 0.15.1
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  rpcPort: 8332
  p2pPort: 8333
  testnetPort: 18332
  testnetP2pPort: 18333

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 10Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
#resources: {}
resources:
#  requests:
#    memory: 512Mi
#    cpu: 300m
  limits:
    cpu: 300m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 1024Mi

# Custom bitcoind configuration file used to override default bitcoind settings
configurationFile:
  bitcoin.conf: |-
    server=1
    printtoconsole=1
    rpcuser=rpcuser
    rpcpassword=rpcpassword
