# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
#  repository: 10.3.252.136:5000/kevinstl/bitcoind-kube
  repository: 10.3.252.136:5000/kevinstl/bitcoind-kube
#  tag: 0.0.6
  tag: 0.0.6
  pullPolicy: IfNotPresent

service:
  rpcPort: 8332
  p2pPort: 8333
  testnetPort: 18332
  testnetP2pPort: 18333

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 10Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
#resources: {}
resources:
#  requests:
#    memory: 512Mi
#    cpu: 300m
  limits:
    cpu: 100m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 2048Mi

# Custom bitcoind configuration file used to override default bitcoind settings
configurationFile:
  bitcoin.conf: |-
    server=1
    rpcuser=devuser_change
    rpcpassword=devpass_change
    testnet=1
    zmqpubrawblock=tcp://127.0.0.1:28332
    zmqpubrawtx=tcp://127.0.0.1:28333
    txindex=1


#    reindex-chainstate=1
#    reindex=1

#    daemon=1
#    printtoconsole=1
#    datadir=/bitcoin

project:    #TODO: Should clean this up. Remove redundancy of network & networkSuffix
  namespace: lightning-kube-simnet
  network: simnet
  networkSuffix: -simnet
  storage: 25Gi