kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lightning-kube-bitcoind-pvcX_NETWORK_SUFFIX_X
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi
  storageClassName: standard
  volumeName: lightning-kube-bitcoind-pvX_NETWORK_SUFFIX_X
