kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitcoind-kube-pvcX_NETWORK_SUFFIX_X
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi
  storageClassName: standard
  volumeName: bitcoind-kube-pvX_NETWORK_SUFFIX_X
