#kubectl apply -f secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: lightning-kube-secrets
type: Opaque
#cat ./setup/config/mlab-keys.json | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' | base64
data:
  mining-address: X_MINING_ADDRESS_X
#  mining-address: ""
